name: Setup Go Compiler
description: Download Go compiler and add to binaries
runs:
  using: composite
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version: ">=1.20.8"
    - run: go version
      shell: bash
