name: e2e tests

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

jobs:
  e2e_test:
    name: e2e tests
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Run e2e tests
        shell: bash
        run: E2E=true scripts/run.sh 1.7.10 0x8db97C7cEcE249c2b98bDC0226Cc4C2A57BF52FC
